language: go

go:
  - 1.x
  - 1.12.x
  - 1.11.x

env:
  - GO111MODULE=on

install: true

before_script:
  - cd /tmp && mkdir tools && cd -
  - sudo curl -s -L "https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.21/nancy-linux.amd64-v0.0.21" -o "/tmp/tools/nancy"
  - sudo chmod +x /tmp/tools/nancy
  - export PATH=$PATH:/tmp/tools/

script:
  - set -e
  - fmt=$(gofmt -l -s .)
  - test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
  - go get golang.org/x/lint/golint
  - golint -set_exit_status $(go list ./...)
  - go test -race -vet=all ./...
  - nancy go.sum

